name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build
      env:
        REACT_APP_WEBSITE_TITLE: ${{ secrets.REACT_APP_WEBSITE_TITLE }}
        REACT_APP_WEBSITE_DESCRIPTION: ${{ secrets.REACT_APP_WEBSITE_DESCRIPTION }}

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl bucket-owner-full-control --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'build'

    - name: Sync content
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl bucket-owner-full-control --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 's3://${{ secrets.AWS_CONTENT_S3_BUCKET }}/'

    - name: Invalidate CloudFront distribution
      uses: chetan/invalidate-cloudfront-action@v1
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}